The Basics

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


Array properties

In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get Shape
b.shape

(2, 3)

In [7]:
# Get Type
a.dtype

dtype('int64')

In [8]:
# Get Size
a.itemsize

8

In [9]:
# Get total size
a.nbytes

24

In [10]:
# Get number of elements
a.size

3

Accessing/Changing specific elements, rows, columns, etc

In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
# Get a specific element [r, c]
print(a[1, 5])

13


In [14]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [16]:
#3D example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get specific element (work outside in)
b[0,1,1]

np.int64(4)

Initializing Different Types of Arrays

In [18]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [20]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [21]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [22]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.77637101, 0.64393567],
       [0.86143063, 0.995445  ],
       [0.7249245 , 0.15107443],
       [0.31126446, 0.10517337]])

In [23]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-3, -1,  2],
       [-1, -1,  3],
       [-4,  5,  3]], dtype=int32)

In [24]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [26]:

# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [33]:
#[1. 1. 1. 1. 1.]
#[1. 0. 0. 0. 1.]
#[1. 0. 9. 0. 1.]
#[1. 0. 0. 0. 1.]
#[1. 1. 1. 1. 1.]
# Create and print above array

#1. Create an array of 1's
output = np.ones((5,5))
print("\n",output)

#2.Create an array of 0's and 9 in middle
z = np.zeros((3,3))
z[1,1] = 9
print("\n",z)

#3.Merge both the array to form the pattern
output[1:4,1:4] = z
print("\n",output)



 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 [[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Careful when copying arrays!!!

In [39]:
a = np.array([1,2,3])
#Wrong way -> b = a (points to same memory location)
#Right way
b = a.copy()
b[0] = 50
print(b)

[50  2  3]


Mathematics


In [40]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [41]:
a + 2

array([3, 4, 5, 6])

In [42]:
a - 2

array([-1,  0,  1,  2])

In [43]:
a * 2

array([2, 4, 6, 8])

In [44]:
a / 2 

array([0.5, 1. , 1.5, 2. ])

In [45]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [46]:
a ** 2

array([ 1,  4,  9, 16])

In [47]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [48]:
# Take the cosine
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Linear Algebra

In [51]:
a = np.ones((2,3))
print("\n",a)

b = np.full((3,2), 2)
print("\n",b)

np.matmul(a,b)


 [[1. 1. 1.]
 [1. 1. 1.]]

 [[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [53]:
# Find the determinant
c = np.identity(3)
det = np.linalg.det(c)
print(det)

1.0


Statistics

In [54]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [55]:
np.min(stats)

np.int64(1)

In [56]:
np.max(stats, axis=1)

array([3, 6])

In [57]:
np.sum(stats, axis=0)

array([5, 7, 9])

Reorganizing Arrays

In [69]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,4))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [70]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [71]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


Numpy Array operations

In [73]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [75]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire col: ", arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire col:  [2 5 8]


Sorting

In [76]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted array " , np.sort(unsorted))

Sorted array  [1 1 2 3 4 5 6 9]


In [83]:
arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column \n", np.sort(arr_2d_unsorted, axis=0))

Sorted 2D array by column 
 [[1 1]
 [2 2]
 [3 3]]


Filter

In [86]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0] #expression evaluate in numpy
print("Even Numbers : " , even_number)

Even Numbers :  [ 2  4  6  8 10]


Filter with Mask

In [88]:
mask = numbers > 5
print("Numbers greater than 5 : ", numbers[mask])

Numbers greater than 5 :  [ 6  7  8  9 10]


Indexing vs np.where()

In [93]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("Numbers greater than 5 : ", numbers[where_result])

[1 3 5]
Numbers greater than 5 :  [ 6  7  8  9 10]


In [94]:
condition_array = np.where(numbers > 5, "true","false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


Array compatibilty

In [96]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes False


In [98]:

original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new column \n", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column 
 [[1 2 7]
 [3 4 8]]


Load Data from File

In [62]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [63]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [67]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [68]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])